[package]
name = "sens-matcher-linux"
version = "0.0.0"
edition = "2021"

[dependencies.enigo]
path = "./enigo-patch"
features = [ "wayland" ]

[dependencies.eframe]
version = "0.29.1"
default-features = false
features = [ "wayland", "glow", "default_fonts" ]
