[package]
name = "sens-matcher-linux"
version = "0.0.0"
edition = "2021"

[dependencies]
egui_dock = "0.14.0"

[dependencies.enigo]
#version = "0.3.0"
path = "./enigo-patch"
features = [ "wayland" ]

[dependencies.eframe]
version = "0.29.1"
default-features = false
features = [ "wayland", "glow", "default_fonts" ]
