[package]
name = "sens-matcher-linux"
version = "0.0.0"
edition = "2021"

[dependencies.eframe]
version = "0.29.1"
default-features = false
features = [ "wayland", "glow", "default_fonts" ]

[dependencies.enigo]
version = "0.3.0"
features = [ "wayland" ]

[patch.crates-io.enigo]
path = "./enigo-patch"
