[package]
name = "sens-matcher-linux"
version = "0.0.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
device_query = "2.1.0"
hyprland = "0.4.0-alpha.1"

[dependencies.tracing-subscriber]
version = "0.3.19"
default-features = false
features = [ "std", "fmt", "ansi" ]

[dependencies.tracing]
version = "0.1.41"
default-features = false
features = [ "std" ]

[dependencies.egui]
version = "0.30.0"
default-features = false
features = [ "default_fonts" ]

[dependencies.eframe]
version = "0.30.0"
default-features = false
features = [ "wayland", "glow" ]

[dependencies.enigo]
version = "0.3.0"
default-features = false
features = [ "xdo", "wayland" ]

[patch.crates-io.enigo]
path = "./enigo-patch"

[dependencies.bon]
version = "3.3.0"
default-features = false
features = [ "std" ]
