[package]
name = "pixel-gauge"
version = "0.0.0"
edition = "2021"

[dependencies]
# Tracing
tracing-subscriber = { version = "0.3.19", default-features = false, features = [ "std", "fmt", "ansi" ] }
tracing = { version = "0.1.41", default-features = false, features = [ "std" ] }

# Egui
egui = { version = "0.30.0", default-features = false, features = [ "default_fonts" ] }
eframe = { version = "0.30.0", default-features = false, features = [ "wayland", "glow" ] }
scarlet-frame = { path = "./scarlet-frame" }

# Input
enigo = { version = "0.3.0", default-features = false, features = [ "xdo", "wayland" ] }
evdev = { version = "0.12.2", default-features = false }

# Utilities
bon = { version = "3.3.0", default-features = false, features = [ "std" ] }
lazy_static = { version = "1.5.0", default-features = false }
